sudo: true
cache: pip
python: "3.7"
language: python

install: # install dependencies (cached)
  - pip install -r requirements.txt
  - pip install --upgrade git+https://github.com/LaunchCodeEducation/sphinx-bootstrap-theme.git@master

script:
  - ./build -c # run clean build

deploy:
  provider: pages # github pages provider
  skip_cleanup: true # save the build output (artifact)
  local_dir: docs # the directory to deploy to GH pages
  github_token: $GITHUB_ACCESS_TOKEN # access token with repo:public scope
  on:
    branch: master # deploy when changes are made to this branch (merging into master)
